/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DTO.brandFullModel;
import DTO.brandModel;
import DAO.brands;
import DTO.motorcycleFullModel;
import DTO.motorcycleModel;
import DAO.motorcycles;
import DBAccess.DBAccess;
import DAO.brandDAO;
import DAO.motorcycleDAO;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.FieldPosition;
import java.text.ParseException;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {

    DBAccess dbAccess = new DBAccess();
    brands brands;
    brandModel brandModel;
    brandFullModel brandFullModel;
    motorcycles cycles;
    motorcycleFullModel cycleModel;
    boolean addNew = false;
    boolean isValid = true;

    /**
     * Creates new form MainFram
     */
    public MainFrame() {
        initComponents();
        brands = new brands();
        brands.loadFromDB(dbAccess);
        cycles = new motorcycles();
        cycles.loadFromDB(dbAccess, brands);
        cycleModel = new motorcycleFullModel(cycles);
        brandFullModel = new brandFullModel(brands);
        setupModel();

    }

    public void setupModel() {
        tblBrand.setModel(brandFullModel);
        tblMotorcycle.setModel(cycleModel);
        this.cbBrandName.setModel(new DefaultComboBoxModel(brands));
    }

    public boolean isEmpty(JTextField txt) {
        if (txt.getText().equals("")) {
            txt.requestFocus(true);
            return true;
        }
        return false;
    }

    public boolean isNumber(JTextField txt) {
        if (!txt.getText().matches("[\\d]+")) {
            return true;
        }
        return false;
    }
    public int findByBrand(String brandID){
        brandModel brand = brands.findBrand(brandID);
        for (int i = 0; i < cycles.size(); i++) {
            if(brand.equals(cycles.get(i).getBrand())) return i;
        }
        return -1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelBrand = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBrandID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBrandName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        btnAddNewBrand = new javax.swing.JButton();
        btnSaveBrand = new javax.swing.JButton();
        btnDeleteBrand = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBrand = new javax.swing.JTable();
        panelMotorcycle = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMotorcycle = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMotorcycleID = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtCondition = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtWarranty = new javax.swing.JTextField();
        cbBrandName = new javax.swing.JComboBox<>();
        btnAddNewMotor = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail part:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BrandID:");

        txtBrandID.setEditable(false);
        txtBrandID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Brand Name: ");

        txtBrandName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Country:");

        txtCountry.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Description:");

        txtDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnAddNewBrand.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddNewBrand.setText("Add New");
        btnAddNewBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewBrandActionPerformed(evt);
            }
        });

        btnSaveBrand.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSaveBrand.setText("Save");
        btnSaveBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBrandActionPerformed(evt);
            }
        });

        btnDeleteBrand.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteBrand.setText("Delete");
        btnDeleteBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBrandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDescription)
            .addComponent(txtCountry)
            .addComponent(txtBrandName)
            .addComponent(txtBrandID)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddNewBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtBrandID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewBrand)
                    .addComponent(btnSaveBrand)
                    .addComponent(btnDeleteBrand))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtCountry.getAccessibleContext().setAccessibleName("txtCountry");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main part:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 0, 255))); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        tblBrand.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBrand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBrandMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblBrandMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblBrand);

        jPanel3.add(jScrollPane2);

        javax.swing.GroupLayout panelBrandLayout = new javax.swing.GroupLayout(panelBrand);
        panelBrand.setLayout(panelBrandLayout);
        panelBrandLayout.setHorizontalGroup(
            panelBrandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBrandLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBrandLayout.setVerticalGroup(
            panelBrandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Brand", panelBrand);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Main part:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 0, 255))); // NOI18N
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        tblMotorcycle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMotorcycle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMotorcycleMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblMotorcycleMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblMotorcycle);

        jPanel5.add(jScrollPane1);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail part:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Motorcucle ID:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Model:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Year:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Condition:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Price:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Quantity:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Warranty:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Brand Name:");

        txtMotorcycleID.setEditable(false);
        txtMotorcycleID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtModel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtCondition.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtWarranty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbBrandName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------Choose a Brand------" }));

        btnAddNewMotor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddNewMotor.setText("AddNew");
        btnAddNewMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewMotorActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnAddNewMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbBrandName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtWarranty)
                            .addComponent(txtQuantity)
                            .addComponent(txtPrice)
                            .addComponent(txtCondition)
                            .addComponent(txtYear)
                            .addComponent(txtModel)
                            .addComponent(txtMotorcycleID))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMotorcycleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewMotor)
                    .addComponent(btnSave)
                    .addComponent(btnDelete))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMotorcycleLayout = new javax.swing.GroupLayout(panelMotorcycle);
        panelMotorcycle.setLayout(panelMotorcycleLayout);
        panelMotorcycleLayout.setHorizontalGroup(
            panelMotorcycleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMotorcycleLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        panelMotorcycleLayout.setVerticalGroup(
            panelMotorcycleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Motorcycle", panelMotorcycle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblBrandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBrandMouseClicked
        // TODO add your handling code here:
        addNew = false;
        int pos = tblBrand.getSelectedRow();
        brandModel brand = brandFullModel.getBrands().get(pos);
        txtBrandID.setText(brand.getBrandID());
        txtBrandID.setEditable(false);
        txtBrandName.setText(brand.getBrandName());
        txtCountry.setText(brand.getCountry());
        txtDescription.setText(brand.getDescription());
    }//GEN-LAST:event_tblBrandMouseClicked

    private void tblBrandMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBrandMouseReleased
        // TODO add your handling code here:
        int row = tblBrand.getSelectedRow();
        int col = tblBrand.getSelectedColumn();
        tblBrand.getCellEditor(row, col).cancelCellEditing();
    }//GEN-LAST:event_tblBrandMouseReleased

    private void btnAddNewBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewBrandActionPerformed
        // TODO add your handling code here:
        txtBrandID.setText("");
        txtBrandID.setEditable(true);
        txtBrandID.requestFocus();
        txtBrandName.setText("");
        txtCountry.setText("");
        txtDescription.setText("");
        addNew = true;
    }//GEN-LAST:event_btnAddNewBrandActionPerformed

    private void btnSaveBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBrandActionPerformed
        int n = 0, m = 0;
        brandDAO brand = new brandDAO();
        brandModel = new brandModel(txtBrandID.getText().toUpperCase(), txtBrandName.getText(), txtCountry.getText(), txtDescription.getText());
//        if (txtBrandID.getText().equals("") || txtBrandName.getText().equals("") || txtCountry.getText().equals("") || txtDescription.getText().equals("")) { 
        if (isEmpty(txtBrandID) || isEmpty(txtBrandName) || isEmpty(txtCountry) || isEmpty(txtDescription)) {
            JOptionPane.showMessageDialog(this, "Please fill sandatory fields");
        } else if (brands.isDuplicated(txtBrandID.getText().toUpperCase())) {
            JOptionPane.showMessageDialog(this, "The BrandID is existed.");
        } else {
            if (addNew == true) {
                n = brand.addNew(brandModel);
            } else {
                m = brand.update(brandModel);
            }
            try {
                if (n > 0 || m > 0) {
                    JOptionPane.showMessageDialog(this, "Add/Update new successful!");
                    if (addNew == false) {
                        int pos = tblBrand.getSelectedRow();
                        brandFullModel.getBrands().set(pos, brandModel);
                    } else {
                        brandFullModel.getBrands().add(brandModel);
                    }
                    tblBrand.updateUI();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_btnSaveBrandActionPerformed

    private void btnDeleteBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBrandActionPerformed
        // TODO add your handling code here:
        int pos = tblBrand.getSelectedRow();
        brandDAO brand = new brandDAO();
        String brandID = txtBrandID.getText().toUpperCase();

        if (findByBrand(brandID) > -1) {
            JOptionPane.showMessageDialog(this, "Can not delete this Brand " + brands.findBrand(brandID).toString());
        } else {
            String msg = " The brand " + brandID + " has been deleted from DB!";
            if (brandID == null) {
                JOptionPane.showMessageDialog(this, "Nothing to delete!!");
            } else {
                try {
                    int n = brand.deleteBrand(brandID);
                    if (n > 0) {
                        JOptionPane.showMessageDialog(this, msg);
                        brandFullModel.getBrands().removeElementAt(pos);
                        tblBrand.updateUI();
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);
                }
            }
        }
    }//GEN-LAST:event_btnDeleteBrandActionPerformed

    private void btnAddNewMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewMotorActionPerformed
        // TODO add your handling code here:
        addNew = true;
        txtMotorcycleID.setText("");
        txtMotorcycleID.setEditable(true);
        txtMotorcycleID.requestFocus();
        txtModel.setText("");
        txtYear.setText("");
        txtCondition.setText("");
        txtPrice.setText("");
        txtQuantity.setText("");
        txtWarranty.setText("");
        cbBrandName.setSelectedItem(0);
    }//GEN-LAST:event_btnAddNewMotorActionPerformed

    private void tblMotorcycleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMotorcycleMouseClicked
        // TODO add your handling code here:
        addNew = false;
        int pos = tblMotorcycle.getSelectedRow();
        motorcycleModel cycle = cycleModel.getCycles().get(pos);
        txtMotorcycleID.setText(cycle.getMotorcycleID());
        txtModel.setText(cycle.getModel());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        txtYear.setText(sdf.format(cycle.getYear()));
        txtCondition.setText(cycle.getCondition());
        txtPrice.setText(String.valueOf(cycle.getPrice()));
        txtQuantity.setText(String.valueOf(cycle.getQuantity()));
        txtWarranty.setText(cycle.getWarranty());
        int index = brands.find(cycle.getBrand().getBrandID());
        cbBrandName.setSelectedIndex(index);
    }//GEN-LAST:event_tblMotorcycleMouseClicked

    private void tblMotorcycleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMotorcycleMouseReleased
        // TODO add your handling code here:
        int row = tblMotorcycle.getSelectedRow();
        int col = tblMotorcycle.getSelectedColumn();
        tblMotorcycle.getCellEditor(row, col).cancelCellEditing();
    }//GEN-LAST:event_tblMotorcycleMouseReleased

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        // TODO add your handling code here:
        String motorcycleID = txtMotorcycleID.getText().toUpperCase();
        String model = txtModel.getText();
        Date year = null;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        if (!txtYear.getText().matches("\\d{4}\\-\\d{2}\\-\\d{2}$")) {
            JOptionPane.showMessageDialog(this, "Wrong input. (yyyy-MM-dd)");
            txtYear.requestFocus();
            return;
        } else {
            year = Date.valueOf(txtYear.getText());
        }
        String condition = txtCondition.getText();
        double price;
        if (isNumber(txtPrice)) {
            JOptionPane.showMessageDialog(this, "Input must be a number");
            txtPrice.requestFocus();
            return;
        } else {
            price = Double.parseDouble(txtPrice.getText());
        }
        int quantity;
        if (isNumber(txtQuantity)) {
            JOptionPane.showMessageDialog(this, "Input must be a number");
            txtQuantity.requestFocus();
            return;
        } else {
            quantity = Integer.parseInt(txtQuantity.getText());
        }
        String warranty = txtWarranty.getText();
        brandModel brand = (brandModel) cbBrandName.getSelectedItem();
        String brandID = brand.getBrandID();
        motorcycleModel cycle;
        cycle = new motorcycleModel(motorcycleID, model, year, condition, price, quantity, warranty, brand);
        motorcycleDAO cycleController = new motorcycleDAO();
        if (isEmpty(txtMotorcycleID) || isEmpty(txtModel) || isEmpty(txtYear) || isEmpty(txtCondition) || isEmpty(txtPrice) || isEmpty(txtQuantity) || isEmpty(txtWarranty)) {
            JOptionPane.showMessageDialog(this, "Please fill sandatory fields");
        } else if (cycles.isDuplicated(motorcycleID)) {
            JOptionPane.showMessageDialog(this, "The motorcycleID is existed!!");
        } else {
            int n = 0, m = 0;
            if (addNew == true) {
                n = cycleController.AddNew(cycle);
            } else {
                m = cycleController.Update(cycle);
            }
            String msg = "An motorcycle has been added/updated.";
            try {
                if (n > 0 || m > 0) {
                    JOptionPane.showMessageDialog(this, msg);
                    if (addNew == false) {
                        int pos = tblMotorcycle.getSelectedRow();
                        cycleModel.getCycles().set(pos, cycle);
                    } else {
                        cycleModel.getCycles().add(cycle);
                    }
                    tblMotorcycle.updateUI();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
            addNew = false;
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int pos = tblMotorcycle.getSelectedRow();
        String motorcycleID = txtMotorcycleID.getText().toUpperCase();
        String sql = " delete from tblBike where motorcycleID='" + motorcycleID + "'";
        JOptionPane.showConfirmDialog(this, "Do you want to delete this motorcycle " + motorcycleID + "?");
        String msg = "The motorcycle " + motorcycleID + " has been deleted from DB!";

        try {
            int n = dbAccess.executeUpdate(sql);
            if (n > 0) {
                JOptionPane.showMessageDialog(this, msg);
                cycleModel.getCycles().removeElementAt(pos);
                tblMotorcycle.updateUI();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewBrand;
    private javax.swing.JButton btnAddNewMotor;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteBrand;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveBrand;
    private javax.swing.JComboBox<String> cbBrandName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelBrand;
    private javax.swing.JPanel panelMotorcycle;
    private javax.swing.JTable tblBrand;
    private javax.swing.JTable tblMotorcycle;
    private javax.swing.JTextField txtBrandID;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtMotorcycleID;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtWarranty;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
